# Generated by Django 3.2.7 on 2021-10-11 20:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Partido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Ciudadano',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=128, unique=True)),
                ('firebaseId', models.CharField(max_length=128, unique=True)),
                ('perfilUrl', models.CharField(max_length=254, null=True)),
                ('dni', models.CharField(default='00000000', max_length=9)),
                ('dniFrontUrl', models.CharField(max_length=254, null=True)),
                ('dniBackUrl', models.CharField(max_length=254, null=True)),
                ('verificado', models.BooleanField(default=False)),
                ('legislador', models.BooleanField(default=False)),
                ('distrito', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='democracia.distrito')),
                ('partido', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='democracia.partido')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
