# Generated by Django 3.2.7 on 2021-10-11 20:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='distrito',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='democracia.distrito'),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='dniBackUrl',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='dniFrontUrl',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='ciudadano',
            name='perfilUrl',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
