# Generated by Django 3.2.7 on 2021-10-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0002_auto_20211011_2046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=128)),
                ('fechaPublicacion', models.DateTimeField()),
                ('contenido', models.TextField(max_length=1024)),
                ('votosPositivos', models.IntegerField(default=0)),
                ('votosNegativos', models.IntegerField(default=0)),
            ],
        ),
    ]
