# Generated by Django 3.2.7 on 2021-10-16 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0004_auto_20211016_0022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ciudadano',
            name='firebaseId',
            field=models.CharField(blank=True, default=None, max_length=128, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='categoria',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='democracia.categoria'),
        ),
    ]
