# Generated by Django 3.2.7 on 2021-10-24 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0005_auto_20211016_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='autores',
            field=models.ManyToManyField(to='democracia.Ciudadano'),
        ),
    ]
