# Generated by Django 3.2.7 on 2021-10-29 01:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0006_idea_autores'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voto', models.CharField(choices=[('P', 'Positivo'), ('N', 'Negativo')], max_length=1)),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.ciudadano')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.idea')),
            ],
        ),
    ]
