# Generated by Django 3.2.7 on 2021-10-29 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0008_auto_20211029_0143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='votosNegativos',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='votosPositivos',
        ),
    ]
