# Generated by Django 3.2.7 on 2021-11-07 03:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0009_auto_20211029_0155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Encuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=512)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.ciudadano')),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.idea')),
            ],
        ),
        migrations.CreateModel(
            name='OpcionEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opcion', models.CharField(max_length=128)),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.encuesta')),
            ],
        ),
        migrations.CreateModel(
            name='VotoEncuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.ciudadano')),
                ('encuesta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.encuesta')),
                ('opcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.opcionencuesta')),
            ],
        ),
    ]
