# Generated by Django 3.2.7 on 2021-11-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0010_encuesta_opcionencuesta_votoencuesta'),
    ]

    operations = [
        migrations.AddField(
            model_name='voto',
            name='fecha',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
