# Generated by Django 3.2.7 on 2021-11-13 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0011_voto_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaMerge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('ideaA', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_a', to='democracia.idea')),
                ('ideaB', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idea_b', to='democracia.idea')),
                ('result', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='democracia.idea')),
            ],
        ),
        migrations.CreateModel(
            name='MergeApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudadano', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.ciudadano')),
                ('merge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='democracia.ideamerge')),
            ],
        ),
    ]
