# Generated by Django 3.2.7 on 2021-11-13 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0012_ideamerge_mergeapproval'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
