# Generated by Django 3.2.7 on 2021-11-14 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0013_idea_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='merge_pendiente',
            field=models.BooleanField(default=False),
        ),
    ]
