# Generated by Django 3.2.7 on 2021-11-22 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('democracia', '0014_idea_merge_pendiente'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='subtitulo',
            field=models.CharField(default='', max_length=256),
        ),
    ]
